---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myappname #FromApplication
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: myappnumber #FromApplication
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordappname #FromApplication
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: wordappnumber #FromApplication
---
