apiVersion: v1
kind: Service
metadata:
  name: mysappname #FromApplication
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysappname #FromApplication
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
